### ISSUE TITLE
UCI Clone Detection paper - "Oreo: detection of clones in the twilight zone"

### ISSUE THREAD

**Issue by marufzaber** [src-d/awesome-machine-learning-on-source-code#191]
This paper uses machine learning to detect clones in the twilight zone. 

"Most clone detectors reported in the literature fail to operate in this zone. We present Oreo, a novel approach to source code clone detection that not only detects Type-1 to Type-3 clones accurately, but is also capable of detecting harder-to-detect clones in the Twilight Zone. Oreo is built using a combination of machine learning, information retrieval, and software metrics. "

**Comment by vmarkovtsev** [comment]
Thanks for the suggestion! Indeed, I discussed this paper in TU Delft a few months ago. Can you please make a PR?

**Comment by marufzaber** [comment]
> Thanks for the suggestion! Indeed, I discussed this paper in TU Delft a few months ago. Can you please make a PR?

No problem. I have created a PR.
