### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by ilya-palachev** [src-d/awesome-machine-learning-on-source-code#196]
Hello,

As I can see, this repository is no longer receiving updates since October 2019. Issues (#193 and #195) and pull requests (#192 and #194) do not receive any response for a long time.

Can anybody of maintainers clarify this situation?

What is the current status of source-d? Is it still maintaining this repository? If no, are there any plans to transfer the responsibility to some other organization?

@vmarkovtsev, @m09, @bzz, @eiso, @EgorBu ?

Thanks in advance.

**Comment by m09** [comment]
Hi @ilya-palachev.

Indeed, as you noticed, this repository is no longer maintained. src-d has closed at the end of last year.

We decided not to maintain it after the closing because there is a good alternative: https://ml4code.github.io/papers.html

Cheers

**Comment by ilya-palachev** [comment]
However, the list that you mentioned is greatly different. A lot of people contributed to your repository, and most of their efforts will not be reflected there... It would be great to merge two lists. How do you think?

**Comment by m09** [comment]
Yes, feel free to fork and merge it's a good idea.

**Comment by bzz** [comment]
Indeed, this list is not maintained any more.

> the list that you mentioned is greatly different

@ilya-palachev Is there anything particular that https://github.com/ml4code/ml4code.github.io is missing that is crucial for your use case?

**Comment by dgrahn** [comment]
A warning should be placed at the top of the repository. I tried to create a pull request for it, but I'm not going to go through all the random hoops to just put a warning message.

**Comment by marnovo** [comment]
As seems I still have rights, added notice and alternative via #198. Let me know.

**Comment by ilya-palachev** [comment]
> As seems I still have rights, added notice and alternative via #198. Let me know.

Okay, thanks!
