### ISSUE TITLE
Add SANER conference

### ISSUE THREAD

**Issue by bzz** [src-d/awesome-machine-learning-on-source-code#56]
IEEE International Conference on "Software Analysis, Evolution and Reengineering" - SANER 2018 had [few papers on "ML on Code"](https://www.conference-publishing.com/list.php?Event=SANER18MAIN) in "Program Analysis", "Defect Prediction" and especially "Language Models" tracks (#57)

Seems worth adding and keeping track of, what do you think?

**Comment by vmarkovtsev** [comment]
+1
