### ISSUE TITLE
Add MS research papers

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/awesome-machine-learning-on-source-code#58]
https://www.microsoft.com/en-us/research/people/mabrocks/

https://www.microsoft.com/en-us/research/blog/learning-source-code

**Comment by vmarkovtsev** [comment]
@egorbu The first link is the collection of papers, should be looked through

**Comment by EgorBu** [comment]
Now I got it, I thought that you just add the author of the `Leaning Source Code`

**Comment by bzz** [comment]
Nice! If I may, I would suggest considering a broader list of papers by the whole "Deep Program Understanding" group. Here is their homepage https://www.microsoft.com/en-us/research/project/program/

**Comment by m09** [comment]
I'm closing this one since we added many of them and follow them closely already.
