### ISSUE TITLE
Videos: add youtube talks section to the list

### ISSUE THREAD

**Issue by bzz** [src-d/awesome-machine-learning-on-source-code#62]
There are some talks on ML on Source Code on youtube already, so would be nice to include those to our list as well.

Here are some candidates from the top of my head and conversation with @eiso :

 - "Neural Abstract Machines & Program Induction Workshop at NIPS 2016" https://www.youtube.com/playlist?list=PLzTDea_cM27LVPSTdK9RypSyqBHZWPywt
 - "source{d} tech talks 2017 - Machine Learning on Source Code" https://www.youtube.com/playlist?list=PL5Ld68ole7j3iQFUSB3fR9122dHCUWXsy
 - "Learning to Code: Machine Learning for Program Induction" https://www.youtube.com/watch?v=vzDuVhFMB9Q

if there is a consensus on usefulness of such section, I would be happy to submit a PR putting it to the suggested place in the ToC.

**Comment by bzz** [comment]
@vmarkovtsev wdyt?

**Comment by vmarkovtsev** [comment]
@bzz All make sense, should go under existing #talks https://github.com/src-d/awesome-machine-learning-on-source-code#talks

**Comment by eiso** [comment]
Closing this since it's in PR stage.
