### ISSUE TITLE
Add an automatic check for PR

### ISSUE THREAD

**Issue by EgorBu** [src-d/awesome-machine-learning-on-source-code#72]
It could be very useful to add an automatic check for PR that will check:
* links haven't been added yet
* links are workable
* duplicate to http://archive.is/

Thanks @bzz for ideas!

**Comment by vmarkovtsev** [comment]
@egorbu this is called TravisCI script step :)

**Comment by EgorBu** [comment]
@vmarkovtsev - updated comment

**Comment by m09** [comment]
Thanks @bzz for implementing this!
