### ISSUE TITLE
[Paper] Program Synthesis for Character Level Language Modeling

### ISSUE THREAD

**Issue by osanwe** [src-d/awesome-machine-learning-on-source-code#74]
Hello,

There is an interesting paper from ICLR 2017 called [Program Synthesis for Character Level Language Modeling](https://www.sri.inf.ethz.ch/papers/charmodel-iclr2017.pdf).

Unfortunatelly I do not remember I got it from your list or not. Currently this paper is not presented here.

If the paper was not removed from the list earlier, I think it is worth to add.

Thank you,
Petr.

**Comment by eiso** [comment]
My apologies for the delayed reply, this should definitely be added. @warenlg can you PR it please?

**Comment by warenlg** [comment]
I don't think it was on the list, but it is definitely an awesome MLonCode paper. Thanks @osanwe.
PR: https://github.com/src-d/awesome-machine-learning-on-source-code/pull/77

**Comment by bzz** [comment]
Closing, as #77 is merged now, but please feel free to re-open if something is not addressed, etc. 
Thank you @osanwe and @warenlg !
