### ISSUE TITLE
Stanford parsing paper "A Fast Unified Model for Parsing and Sentence Understanding"

### ISSUE THREAD

**Issue by m09** [src-d/awesome-machine-learning-on-source-code#86]
Includes ideas from classical parsing in NLP (shift reduce parser) + ideas from TreeRNNs and adds a way to track linear history that was lacking in them.

Seems really relevant to code comprehension and modelling of UASTs. I guess it should fit in the related research section.

https://arxiv.org/abs/1603.06021

**Comment by vmarkovtsev** [comment]
@m09 +1, pls PR
