### ISSUE TITLE
Add modelforge to libraries

### ISSUE THREAD

**Issue by marnovo** [src-d/awesome-machine-learning-on-source-code#9]
Add [src-d/modelforge](https://www.github.com/src-d/modelforge) to the libraries.

**Comment by vmarkovtsev** [comment]
I am not sure if we should... It is a general purpose model API and storage, has nothing to do with MLoSC

**Comment by marnovo** [comment]
It will be **the** go-to place for all MLoSC models, no?

**Comment by vmarkovtsev** [comment]
We've got a confusion here: we've called "modelforge" the Python package and the storage registry. We need to rename the latter to sourcedforge or smth. Damn, sourcedforge reads like sourceforge

**Comment by eiso** [comment]
@vmarkovtsev can I close this with the latest updates to modelforge?

**Comment by m09** [comment]
WDYT @vmarkovtsev? Should we add it or close this issue?

**Comment by vmarkovtsev** [comment]
Now that we have src-d/models, we should definitely add it and then close this.
